/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.web.surya;

import id.web.surya.models.Mahasiswa;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Mahasiswa mhs = new Mahasiswa();
        
        mhs.nim = "a12345678";
        mhs.nama = "nama mu";
        mhs.jmlSks = 144;
        mhs.ipk = 3.95;
        mhs.addHP("0123123123");
        mhs.addHP("082389471920843");
        mhs.addHP("0928934038");
        mhs.addHP("01827634289");

        mhs.cetakLap();

    }
}
